# -*- coding: utf-8 -*-
"""5001HW2_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XpTIPe_Ux4vT9SJjtahGUCNMCj8YOAmt

1. A **ZeroDivisionError** occurs when second operand of division or modulus operation is zero.
"""

print(1/0)

"""Division by zero is undefined in mathematics, and division by zero in Python is illegal.

2. **SyntaxError**:A syntax error is a common error that the interpreter can detect when attempting to translate a Python statement into machine language.
"""

y = 5
x = y + 2
y + 2 = x

"""The syntax of Python doesn't allow an expression like y + 2 to appear on the left side of the assignment operartor.

3. An **IndexError** occurs when a sequence (list, string, tuple) index is out of range.
"""

seq = [2, 5, 11]
print(seq[3])

"""'3' is out of range of the list'seq' index, which induces an IndexError.

4. A **NameError** occurs when Specified local or global name does not exists
"""

print(x)

"""x is not defined previously, which induces a NameError."""