# -*- coding: utf-8 -*-
"""HW2_Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tv8Vo5c1W_bqB_RwsZ08IU4w0LpkP1M9

## **A Boolean function called is_leap_year**
"""

def is_leap_year(year):
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False

"""## **Main Function with examples tested**"""

if __name__  == "__main__":
    year = int(input("Please enter a year greater than 0:"))
    # input 1999
    if is_leap_year(year):
        print(f'The year {year} is a leap year')
    else:
        print(f'The year {year} is not a leap year')

if __name__  == "__main__":
    year = int(input("Please enter a year greater than 0:"))
    # input 2000
    if is_leap_year(year):
        print(f'The year {year} is a leap year')
    else:
        print(f'The year {year} is not a leap year')

if __name__  == "__main__":
    year = int(input("Please enter a year greater than 0:"))
    # input 2001
    if is_leap_year(year):
        print(f'The year {year} is a leap year')
    else:
        print(f'The year {year} is not a leap year')

if __name__  == "__main__":
    year = int(input("Please enter a year greater than 0:"))
    # input 2002
    if is_leap_year(year):
        print(f'The year {year} is a leap year')
    else:
        print(f'The year {year} is not a leap year')

if __name__  == "__main__":
    year = int(input("Please enter a year greater than 0:"))
     # input 2003
    if is_leap_year(year):
        print(f'The year {year} is a leap year')
    else:
        print(f'The year {year} is not a leap year')

if __name__  == "__main__":
    year = int(input("Please enter a year greater than 0:"))
    # input 2028
    if is_leap_year(year):
        print(f'The year {year} is a leap year')
    else:
        print(f'The year {year} is not a leap year')